run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 30m

  modules-download-mode: readonly

  go: '1.22'

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # default is "colored-line-number"
  formats: code-climate

linters:
  enable-all: false
  disable:
    - exhaustruct
    - gofumpt
    - testpackage
    - depguard
    - tagliatelle
    - ireturn
    - varnamelen
    - wrapcheck

linters-settings:
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    # https://staticcheck.io/docs/options#checks
    checks: [ "all", "-ST1000" ]
  funlen:
    lines: 100
  gci:
    sections:
      - standard
      - default
      - prefix(gitlab.sima-land.ru/sl/it/dev-dep/web-services/ad-data-operator)
  gocyclo:
    min-complexity: 5
  varnamelen:
    ignore-names:
      - id
    ignore-decls:
      - ok bool
  wrapcheck:
    ignorePackageGlobs:
      - google.golang.org/grpc/status
      - github.com/pkg/errors
      - golang.org/x/sync/errgroup
  gosec:
    excludes:
      - G204

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - gocyclo
        - cyclop
        - funlen
        - goerr113
        - varnamelen
        - staticcheck
        - maintidx
        - lll
        - paralleltest
        - dupl
        - typecheck
        - wsl
    - path: main\.go
      linters:
        - gochecknoglobals
        - lll
        - funlen
